services:
  nginx:
    container_name: laravel-bet_nginx
    image: nginx
    volumes:
      - ./:/var/www/laravel-bet
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - mongodb
    restart: always
    networks:
      - laravel_network

  php-fpm:
    container_name: laravel-bet_php
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/laravel-bet
    networks:
      - laravel_network
    depends_on:
      - mongodb

  mongodb:
    container_name: laravel-bet_mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - laravel_network

  redis:
      container_name: laravel-bet_redis
      image: redis
      restart: always
      ports:
        - "6379:6379"
      networks:
        - laravel_network

  rabbitmq:
    container_name: laravel-bet_rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
